import assert from 'node:assert';

import { projects } from '../../../db/schema';
import Project, { type IProject } from '../../models/project';
import type { ProjectsRepository } from './types';
import type { HonoContext } from '../../../context';
import { getSession } from '../../../context/session';
import { getDrizzle } from '../../../context/database';

class ProjectsRepositoryImpl implements ProjectsRepository {
  private readonly context: HonoContext;

  constructor(params: { context: HonoContext }) {
    this.context = params.context;
  }

  createProject = async (payload: Omit<IProject, 'id'>): Promise<Project> => {
    assert(
      getSession(this.context)?.user.id === payload.userId,
      'This function should only get called with a user id of the logged in user',
    );

    const project = new Project({ ...payload, id: null });
    assert(project.id, 'ID should have gotten generated by the constructor of Project');

    await getDrizzle(this.context).insert(projects).values(project);

    return project;
  };
}

export default ProjectsRepositoryImpl;
