import assert from 'node:assert';

import { projects } from '../../../db/schema';
import type Project from '../../models/project';
import { newProject, type IProject } from '../../models/project';
import type { ProjectsRepository } from './types';
import type { HonoContext } from '../../../context';
import { getSession } from '../../../context/session';
import { getDrizzle } from '../../../context/database';
import { getLogger } from '../../../context/logging';
import { ProjectNameAlreadyExists } from '../../exceptions';
import type { SessionResponse } from '../../../auth';

class ProjectsRepositoryImpl implements ProjectsRepository {
  private readonly context: HonoContext;

  constructor(params: { context: HonoContext }) {
    this.context = params.context;
  }

  createProject = async (payload: Omit<IProject, 'id' | 'userId'>): Promise<Project> => {
    const session = this.getSession();
    const project = newProject({ ...payload, userId: session.user.id, id: null });
    assert(project.id, 'ID should have gotten generated by the constructor of Project');

    const result = await getDrizzle(this.context).insert(projects).values(project).onConflictDoNothing();
    if (result.rowCount === 0) {
      getLogger(this.context).error('Project name already exists for user', {
        project_name: payload.name,
      });
      throw new ProjectNameAlreadyExists(this.context);
    }

    return project;
  };

  list = async (): Promise<Project[]> => {
    const session = this.getSession();
    const usersProjects = await getDrizzle(this.context).query.projects.findMany({ with: { userId: session.user.id } });

    return usersProjects.map(newProject);
  };

  read = async (id: string): Promise<Project | null> => {
    const session = this.getSession();
    const project = await getDrizzle(this.context).query.projects.findFirst({ with: { userId: session.user.id, id } });
    if (project == null) {
      return null;
    }

    return newProject(project);
  };

  private getSession = (): SessionResponse => {
    const session = getSession(this.context);
    assert(session != null, 'This function should have been called with an authorized request');

    return session;
  };
}

export default ProjectsRepositoryImpl;
