import assert from 'node:assert';

import type { DrizzleDatabase } from '../../../db';
import { projects } from '../../../db/schema';
import Project, { type IProject } from '../../models/project';
import type { ProjectsRepository } from './types';

class ProjectsPostgresRepository implements ProjectsRepository {
  private readonly drizzle: DrizzleDatabase;

  constructor(drizzle: DrizzleDatabase) {
    this.drizzle = drizzle;
  }

  createProject = async (payload: Omit<IProject, 'id'>): Promise<Project> => {
    const project = new Project({ ...payload, id: null });
    assert(project.id, 'ID should have gotten generated by the constructor of Project');

    await this.drizzle.insert(projects).values(project);

    return project;
  };
}

export default ProjectsPostgresRepository;
