# List available commands
[group('meta')]
default:
    just --list --unsorted

# Run dev server
[group('development')]
dev: prepare
    bun run dev

# Prepare project for development
[group('development')]
prepare: install-modules

# Install modules
[group('development')]
install-modules:
    bun install
